### ISSUE TITLE
Api manager

### ISSUE THREAD

**Issue by Ramon96** [Ramon96/aria-1920#4]
We gaan tijdens dit project met veel Api's aan de slag lijkt me goed om een paar functie's op te zetten die api data kunnen ophalen, kunnen opschonen ETC

**Comment by TomasS666** [comment]
After the code review with Janno, we concluded that the best way to handle this is as followed:
1. We have our our API folder structure with a central Express server and routes, this is handled as serverMiddleware within Nuxt and runs kinda seperate from our application.
2. Within the routes of this middleware we define logic for each and every API we are gonna use.

3. General helpers and data manipulation, etc. that can be done in a module, but specific API data handling is done within a route

4. In our serverMiddleware we setup endpoints, from the client we fetch (fetch, axios.get()) our own endpoints => endpoint on the server does call to external API => endpoint retrieves data and sends it in JSON format back to our client. 

5. Components can then be rendered. We have to checkout the asyncData lifecycle. And where it lives, where stuff is rendered / client or server. Because if this is indeed semi SSR, we're good. If it's not perse, we might want to check if we can render the snippets on the server already another way.
